//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcUEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryDetails
    {
        public int Id { get; set; }
        public Nullable<int> GalleryMasterId { get; set; }
        public string TitleMk { get; set; }
        public string TitleFr { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    }
}
